# Generated by Django 3.2.9 on 2021-11-18 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_status',
            field=models.CharField(choices=[('Черновая отделка', 'Черновая отделка'), ('Требует ремонта', 'Требует ремонта'), ('Требуется капитальный ремонт', 'Требуется капитальный ремонт')], max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='document',
            field=models.CharField(choices=[('Документ собственности', 'Документ собственности'), ('Доверенность', 'Доверенность')], max_length=255, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.house', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления'),
        ),
    ]
