# Generated by Django 3.2.9 on 2021-11-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contact',
            field=models.CharField(choices=[('CALL', 'Звонок'), ('MESSAGE', 'Сообщение'), ('CALL&MES', 'Звонок + сообщение')], max_length=12, verbose_name='Способ связи'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='payment',
            field=models.CharField(choices=[('CAPITAL', 'Мат. капитал'), ('MORTGAGE', 'Ипотека'), ('CAP&MORT', 'Мат. капитал, Ипотека')], max_length=8, verbose_name='Варианты расчёта'),
        ),
    ]
