# Generated by Django 3.2.9 on 2021-11-19 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserApartRelation',
            new_name='UserApart',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='room_count',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='notification',
            new_name='notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='subscribe_expired',
            new_name='subscription_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='subscribe',
            new_name='switch',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='adv_type',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_area',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_status',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_type',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='heating_type',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='settlement_type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='building_technologies',
        ),
        migrations.RemoveField(
            model_name='house',
            name='current_status',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apart_area',
            field=models.FloatField(default=1, verbose_name='Общая площадь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='apart_status',
            field=models.CharField(choices=[('SHELL', 'Черновая'), ('REPAIR', 'Требует ремонта'), ('FULL REPAIR', 'Требуется капитальный ремонт')], default='SHELL', max_length=11, verbose_name='Жилое состояние'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='apart_type',
            field=models.CharField(choices=[('APARTMENT', 'Апартаменты'), ('PENTHOUSE', 'Пентхаус')], default='APARTMENT', max_length=9, verbose_name='Назначение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='heating',
            field=models.CharField(choices=[('GAS', 'Газовое'), ('WOOD', 'Дрова')], default='GAS', max_length=4, verbose_name='Отопление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='payment',
            field=models.CharField(choices=[('CAPITAL', 'Мат. капитал'), ('MORTGAGE', 'Ипотека'), ('C&M', 'Мат. капитал, Ипотека')], default='MORTGAGE', max_length=8, verbose_name='Варианты расчёта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='building_technology',
            field=models.CharField(choices=[('MONOLITHIC', 'Монолитный каркас с керамзитно-блочным заполнением'), ('PANEL', 'Панельный'), ('BRICK', 'Кирпич')], default='MONO', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='ceiling',
            field=models.FloatField(default=2, verbose_name='Высота потолков'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('SECONDARY', 'Вторичный рынок'), ('NEW', 'Новостройки'), ('COTTAGE', 'Коттедж')], default='NEW', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='title',
            field=models.CharField(default='ЖК', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apart_class',
            field=models.CharField(choices=[('STUDIO', 'Студия, санузел'), ('GUEST', 'Гостинка'), ('SMALL', 'Малосемейка'), ('ISOLATED', 'Изолированные комнаты'), ('ADJOINING', 'Смежные комнаты'), ('FREE', 'Свободная планировка')], max_length=9, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='commission',
            field=models.FloatField(verbose_name='Комиссия агенту'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contact',
            field=models.CharField(choices=[('CALL', 'Звонок'), ('CALL&MESSAGE', 'Звонок + сообщение')], max_length=12, verbose_name='Способ связи'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='document',
            field=models.CharField(choices=[('OWNERSHIP', 'Документ собственности'), ('POA', 'Доверенность')], max_length=9, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='house',
            name='distance_to_sea',
            field=models.FloatField(verbose_name='Расстояние до моря'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating',
            field=models.CharField(choices=[('CENTRAL', 'Центральное'), ('PERSONAL', 'Индивидуальное')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_status',
            field=models.CharField(choices=[('ELITE', 'Элитный'), ('NOT LEASED', 'Не сдан')], max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('MULTI', 'Многоквартирный'), ('NOT LEASED', 'Не сдан')], max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='territory_type',
            field=models.CharField(choices=[('CLOSED', 'Закрытая'), ('OPEN', 'Открытая')], max_length=255, verbose_name='Территория'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA', unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Клиент'), ('AGENT', 'Агент'), ('NOTARY', 'Нотариус'), ('DEPART', 'Отдел продаж'), ('SYSTEM', 'Администрация Swipe')], default='USER', max_length=6),
        ),
        migrations.DeleteModel(
            name='ApartImgRelations',
        ),
        migrations.AddField(
            model_name='houseimg',
            name='apart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house'),
        ),
        migrations.AddField(
            model_name='apartimg',
            name='apart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apartment'),
        ),
    ]
