# Generated by Django 3.2.9 on 2021-11-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211120_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseNews',
            new_name='HouseNew',
        ),
        migrations.AlterField(
            model_name='house',
            name='building_technology',
            field=models.CharField(choices=[('MONO', 'Монолитный каркас с керамзитно-блочным заполнением'), ('PANEL', 'Панельный'), ('BRICK', 'Кирпич')], max_length=255),
        ),
    ]
