# Generated by Django 4.0 on 2021-12-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='water',
            field=models.CharField(choices=[('CENTRAL', 'Центральное'), ('AUTO', 'Автономное')], max_length=8, verbose_name='Водоснабжение'),
        ),
    ]
