# Generated by Django 3.2.9 on 2021-11-19 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211120_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='building_technology',
        ),
        migrations.RemoveField(
            model_name='house',
            name='celling_height',
        ),
        migrations.RemoveField(
            model_name='house',
            name='distance_to_sea',
        ),
        migrations.RemoveField(
            model_name='house',
            name='invoice_options',
        ),
        migrations.RemoveField(
            model_name='house',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='registration_type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='territory_type',
        ),
        migrations.AddField(
            model_name='house',
            name='doc_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Варианты оформления'),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity',
            field=models.BooleanField(default=False, verbose_name='Электричество'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_leased',
            field=models.CharField(choices=[('LEASED', 'Сдан'), ('NOT LEASED', 'Не сдан')], default='LEASED', max_length=10, verbose_name='Эксплуатация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='pay_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Варианты расчёта'),
        ),
        migrations.AddField(
            model_name='house',
            name='sea',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние до моря'),
        ),
        migrations.AddField(
            model_name='house',
            name='sewerage',
            field=models.CharField(choices=[('CENTRAL', 'Центральная'), ('PIT', 'Яма')], default='CENTRAL', max_length=8, verbose_name='Канализация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='technology',
            field=models.CharField(choices=[('MONO', 'Монолитный каркас с керамзитно-блочным заполнением'), ('PANEL', 'Панельный'), ('BRICK', 'Кирпич')], default='MONO', max_length=10, verbose_name='Технология строительства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='territory',
            field=models.CharField(choices=[('CLOSED', 'Закрытая'), ('OPEN', 'Открытая')], default='CLOSED', max_length=10, verbose_name='Территория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='ceiling',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='house',
            name='contract_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма в договоре'),
        ),
        migrations.AlterField(
            model_name='house',
            name='gas',
            field=models.BooleanField(default=False, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='heating',
            field=models.CharField(choices=[('CENTRAL', 'Центральное'), ('PERSONAL', 'Индивидуальное')], max_length=8, null=True, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_status',
            field=models.CharField(choices=[('ECO', 'Эконом'), ('COMFORT', 'Комфорт'), ('COMFORT', 'Бизнес'), ('ELITE', 'Элитный')], max_length=10, verbose_name='Статус ЖК'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('MULTI', 'Многоквартирный'), ('PRIVATE', 'Частный')], max_length=10, verbose_name='Вид дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('SECONDARY', 'Вторичный рынок'), ('NEW', 'Новостройки'), ('COTTAGE', 'Коттедж')], max_length=10, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='house',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='water',
            field=models.CharField(choices=[('SEWERAGE', 'Центральное'), ('AUTO', 'Автономное')], max_length=8, verbose_name='Водоснабжение'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='housedoc',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house'),
        ),
    ]
