# Generated by Django 4.0 on 2021-12-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_house_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='heating',
            field=models.CharField(choices=[('GAS', 'Газовое'), ('ELECTRO', 'Электрическое'), ('WOOD', 'Дрова')], max_length=7, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_status',
            field=models.CharField(choices=[('ECO', 'Эконом'), ('COMFORT', 'Комфорт'), ('BUSINESS', 'Бизнес'), ('ELITE', 'Элитный')], max_length=10, verbose_name='Статус ЖК'),
        ),
    ]
