# Generated by Django 3.2.9 on 2021-11-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211120_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Инфраструктура ЖК'),
        ),
    ]
