# Generated by Django 3.2.9 on 2021-11-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_house_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='purpose',
        ),
    ]
