# Generated by Django 3.2.9 on 2021-11-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_house_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='manager',
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус недвижимости'),
        ),
    ]
