# Generated by Django 3.2.9 on 2021-11-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211120_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='floor',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Секция'),
            preserve_default=False,
        ),
    ]
