# Generated by Django 3.2.9 on 2021-11-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211120_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveSmallIntegerField(verbose_name='Количество комнат'),
        ),
    ]
