# Generated by Django 3.2.9 on 2021-11-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_apartment_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promotion', verbose_name='Продвижение'),
        ),
    ]
