# Generated by Django 3.2.9 on 2021-11-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_apartment_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apart_status',
            field=models.CharField(choices=[('SHELL', 'Черновая'), ('EURO', 'Евроремонт'), ('REPAIR', 'Требует ремонта'), ('FULL REPAIR', 'Требуется капитальный ремонт')], max_length=11, verbose_name='Жилое состояние'),
        ),
    ]
