# Generated by Django 3.2.9 on 2021-11-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_apartment_apart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimg',
            name='apart',
        ),
        migrations.AddField(
            model_name='houseimg',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.house', verbose_name='ЖК'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartimg',
            name='apart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='apartimg',
            name='image',
            field=models.ImageField(upload_to='apartments/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_actual',
            field=models.BooleanField(default=False, verbose_name='Актуально'),
        ),
        migrations.AlterField(
            model_name='houseimg',
            name='image',
            field=models.ImageField(upload_to='houses/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='color',
            field=models.CharField(choices=[('Красный', 'Красный'), ('Зелёный', 'Зелёный'), ('Синий', 'Синий'), ('Желтый', 'Желтый')], max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('Большое объявление', 'Большое объявление'), ('Поднять объявление', 'Поднять объявление'), ('Турбо', 'Турбо')], max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
