# Generated by Django 3.2.9 on 2021-11-20 00:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211120_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartimg',
            options={'verbose_name': 'Фото квартиры', 'verbose_name_plural': 'Фото квартиры'},
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='housedoc',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='houseimg',
            options={'verbose_name': 'Фото дома', 'verbose_name_plural': 'Фото дома'},
        ),
        migrations.AlterModelOptions(
            name='housenew',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Продвижение', 'verbose_name_plural': 'Продвижение'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секцию', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='apart_class',
            new_name='apart_layout',
        ),
        migrations.AlterField(
            model_name='housedoc',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='housedoc',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email агента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя агента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия агента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', verbose_name='Телефон агента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.CharField(choices=[('ME', 'Мне'), ('MEANDAGENT', 'Мне и агенту'), ('AGENT', 'Агенту'), ('OFF', 'Отключить')], default='ME', max_length=10, verbose_name='Уведомления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Клиент'), ('AGENT', 'Агент'), ('NOTARY', 'Нотариус'), ('DEPART', 'Отдел продаж'), ('SYSTEM', 'Администрация Swipe')], default='USER', max_length=6, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='switch',
            field=models.BooleanField(default=False, verbose_name='Переключить звонки и сообщения на агента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Верификация пройдена'),
        ),
    ]
